# This workflow builds AUGUSTUS and executes the 
# longrunning test cases
name: Execute AUGUSTUS longrunning test cases

on:
  push:
    branches:
      - master
#      - 'longrunning_tests'

  #schedule:
  # execute workflow at scheduled time
  #- cron:  '30 1 * * *'

env:
  TOOLDIR: /data/tools

jobs:
  longrunning_test:
    runs-on: [self-hosted, linux, ubuntu]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build AUGUSTUS
      run: make all

    - name: Execute single genome test cases
      run: ./test_single.sh -e /data/eval/
      working-directory: tests/longrunning/single_genome/

    - name: Extract desired accuracy values
      run: ./extract_accuracy_values.py --path single_genome/output/eval
      working-directory: tests/longrunning/
