# This workflow builds AUGUSTUS and executes the 
# longrunning test cases
name: Execute AUGUSTUS longrunning test cases

on:
  push:
    branches:
      - 'test_gh_shr'

  #schedule:
  # execute workflow at scheduled time
  #- cron:  '30 1 * * *'

env:
  TOOLDIR: /data/tools

jobs:
  longrunning_test:
    runs-on: [self-hosted, linux]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build AUGUSTUS
      run: make all

    - name: Execute test cases
      run: ./execute_test.py --data ../examples --eval /data/eval
      working-directory: ./longrunning_examples
