# This workflow builds AUGUSTUS and executes the 
# longrunning test cases
name: Execute AUGUSTUS longrunning test cases

on:
  push:
    branches:
      - 'testing'

  #schedule:
  # execute workflow at scheduled time
  #- cron:  '30 1 * * *'

env:
  TOOLDIR: /data/tools

jobs:
  longrunning_test:
    runs-on: [self-hosted, linux]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Build AUGUSTUS
      run: make all

#    - name: Execute test cases
#      run: ./execute_test.py --data /home/daniel/data/examples --eval /home/daniel/eval-2.2.8
#      working-directory: ./longrunning_examples
